site_name: Cedric Champoux
site_url: https://Guerre450.github.io/
theme:
  name: simple-blog
  sidebar : true
  navigation_depth : 3
  components:
    title: false
    footer : false
plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
  - search:
      enabled: true
  - simple-blog-posts: